version: 2
jobs:
    # Latest build
    build:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.1
            - run: ./publish.sh 7.1

    build-5.6:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 5.6
            - run: ./publish.sh 5.6


workflows:
    version: 2

    build_versions:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master
            - build-5.6:
                filters:
                    branches:
                        only:
                            - master
