version: 2
jobs:
    # Latest build
    build:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.2 --no-cache
            - run: ./publish.sh 7.2

    build-7.1:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.1 --no-cache
            - run: ./publish.sh 7.1

workflows:
    version: 2

    build_versions:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master

            - build-7.1:
                filters:
                    branches:
                        only:
                            - master

    weekly_builds:
        triggers:
            - schedule:
                cron: "0 10 * * 1"
                filters:
                    branches:
                        only:
                            - master
        jobs:
            - build
            - build-7.1
