version: 2
jobs:
    build:
        machine: true
        steps:
            - checkout

    5.6:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 5.6

    7.1:
        machine: true
        steps:
            - checkout
            - run: ./build.sh 7.1

workflows:
    version: 2

    build_versions:
        jobs:
            - build:
                filters:
                    branches:
                        only:
                            - master

            - 5.6:
                requires:
                    - build

            - 7.1:
                requires:
                    - build
